import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:google_sign_in/google_sign_in.dart';
import 'package:http/http.dart' as http;
import 'package:intl/intl.dart';
import 'package:provider/provider.dart';

const apiUrl = String.fromEnvironment('API_URL', defaultValue: 'http://10.0.2.2:8080');

void main() => runApp(ChangeNotifierProvider(create: (_) => FinanceStore(), child: const FinoraApp()));

class FinanceStore extends ChangeNotifier {
  String? token;
  Map<String, dynamic>? user;
  List<dynamic> transactions = [];
  Map<String, dynamic> report = {'income': 0, 'expense': 0, 'balance': 0};
  bool loading = false;

  Map<String, String> get headers => {'Content-Type': 'application/json', if (token != null) 'Authorization': 'Bearer $token'};
  Future<Map<String, dynamic>> call(String path, {String method = 'GET', Map<String, dynamic>? body}) async {
    final uri = Uri.parse('$apiUrl$path');
    final response = method == 'POST' ? await http.post(uri, headers: headers, body: jsonEncode(body)) : method == 'DELETE' ? await http.delete(uri, headers: headers) : await http.get(uri, headers: headers);
    final data = jsonDecode(response.body) as Map<String, dynamic>;
    if (response.statusCode >= 400) throw Exception(data['error'] ?? 'Có lỗi xảy ra');
    return data;
  }

  Future<void> login(String email, String password) async { final data = await call('/login', method: 'POST', body: {'email': email, 'password': password}); token = data['token']; user = data['user']; await load(); notifyListeners(); }
  Future<void> register(String name, String email, String password) async { final data = await call('/register', method: 'POST', body: {'name': name, 'email': email, 'password': password}); token = data['token']; user = data['user']; await load(); notifyListeners(); }
  Future<void> googleLogin() async { final account = await GoogleSignIn(scopes: ['email']).signIn(); if (account == null) return; final auth = await account.authentication; if (auth.idToken == null) throw Exception('Không lấy được Google token'); }
  Future<void> load() async { loading = true; notifyListeners(); try { final list = await call('/transactions'); final summary = await call('/reports'); transactions = list as List<dynamic>; report = summary; } finally { loading = false; notifyListeners(); } }
  Future<void> add(double amount, String description, String type) async { await call('/transactions', method: 'POST', body: {'amount': amount, 'description': description, 'type': type}); await load(); }
  Future<void> remove(int id) async { await call('/transactions/$id', method: 'DELETE'); await load(); }
  void logout() { token = null; user = null; transactions = []; report = {'income': 0, 'expense': 0, 'balance': 0}; notifyListeners(); }
}

class FinoraApp extends StatelessWidget { const FinoraApp({super.key}); @override Widget build(BuildContext context) => MaterialApp(debugShowCheckedModeBanner: false, title: 'Finora', theme: ThemeData(useMaterial3: true, colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xff32b48b)), fontFamily: 'Arial'), home: Consumer<FinanceStore>(builder: (_, store, __) => store.token == null ? const LoginScreen() : const HomeScreen())); }

class LoginScreen extends StatefulWidget { const LoginScreen({super.key}); @override State<LoginScreen> createState() => _LoginScreenState(); }
class _LoginScreenState extends State<LoginScreen> {
  final email = TextEditingController(), password = TextEditingController(), name = TextEditingController(); bool register = false, busy = false;
  Future<void> submit() async { setState(() => busy = true); try { final store = context.read<FinanceStore>(); register ? await store.register(name.text, email.text, password.text) : await store.login(email.text, password.text); } catch (e) { if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(e.toString().replaceFirst('Exception: ', '')))); } finally { if (mounted) setState(() => busy = false); } }
  @override Widget build(BuildContext context) => Scaffold(backgroundColor: const Color(0xff0e1726), body: SafeArea(child: Center(child: SingleChildScrollView(padding: const EdgeInsets.all(28), child: Card(child: Padding(padding: const EdgeInsets.all(24), child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [const Icon(Icons.trending_up, color: Color(0xff32b48b), size: 42), const SizedBox(height: 12), const Text('finora', textAlign: TextAlign.center, style: TextStyle(fontSize: 28, fontWeight: FontWeight.bold)), const SizedBox(height: 8), Text(register ? 'Tạo tài khoản mới' : 'Chào mừng trở lại', textAlign: TextAlign.center, style: const TextStyle(fontSize: 22, fontWeight: FontWeight.w600)), const SizedBox(height: 24), if (register) TextField(controller: name, decoration: const InputDecoration(labelText: 'Họ và tên')), TextField(controller: email, decoration: const InputDecoration(labelText: 'Email')), TextField(controller: password, obscureText: true, decoration: const InputDecoration(labelText: 'Mật khẩu')), const SizedBox(height: 20), FilledButton(onPressed: busy ? null : submit, child: Text(busy ? 'Đang xử lý...' : register ? 'Đăng ký' : 'Đăng nhập')), OutlinedButton.icon(onPressed: () => context.read<FinanceStore>().googleLogin(), icon: const Icon(Icons.login), label: const Text('Đăng nhập bằng Google')), TextButton(onPressed: () => setState(() => register = !register), child: Text(register ? 'Đã có tài khoản? Đăng nhập' : 'Chưa có tài khoản? Đăng ký'))]))))));
}

class HomeScreen extends StatefulWidget { const HomeScreen({super.key}); @override State<HomeScreen> createState() => _HomeScreenState(); }
class _HomeScreenState extends State<HomeScreen> { int tab = 0; @override void initState() { super.initState(); Future.microtask(() => context.read<FinanceStore>().load()); } @override Widget build(BuildContext context) { final pages = [const DashboardTab(), const TransactionsTab(), const ReportTab()]; return Scaffold(appBar: AppBar(title: const Text('finora', style: TextStyle(fontWeight: FontWeight.bold)), actions: [IconButton(onPressed: () => context.read<FinanceStore>().logout(), icon: const Icon(Icons.logout))]), body: pages[tab], bottomNavigationBar: NavigationBar(selectedIndex: tab, onDestinationSelected: (i) => setState(() => tab = i), destinations: const [NavigationDestination(icon: Icon(Icons.dashboard_outlined), label: 'Tổng quan'), NavigationDestination(icon: Icon(Icons.swap_horiz), label: 'Giao dịch'), NavigationDestination(icon: Icon(Icons.pie_chart_outline), label: 'Báo cáo')]),); } }

String money(num value) => NumberFormat.currency(locale: 'vi_VN', symbol: '₫', decimalDigits: 0).format(value);
class DashboardTab extends StatelessWidget { const DashboardTab({super.key}); @override Widget build(BuildContext context) { final s = context.watch<FinanceStore>(); return RefreshIndicator(onRefresh: s.load, child: ListView(padding: const EdgeInsets.all(18), children: [Text('Xin chào, ${s.user?['name'] ?? 'bạn'}', style: const TextStyle(color: Colors.grey)), const SizedBox(height: 6), Card(color: const Color(0xff0e1726), child: Padding(padding: const EdgeInsets.all(22), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('Số dư hiện tại', style: TextStyle(color: Colors.white70)), Text(money(s.report['balance'] ?? 0), style: const TextStyle(color: Colors.white, fontSize: 30, fontWeight: FontWeight.bold))])), const SizedBox(height: 12), Row(children: [Expanded(child: Metric(label: 'Thu nhập', value: s.report['income'] ?? 0, color: Colors.green)), Expanded(child: Metric(label: 'Chi tiêu', value: s.report['expense'] ?? 0, color: Colors.red))]), const SizedBox(height: 20), const Text('Giao dịch gần đây', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)), ...s.transactions.take(5).map((x) => TransactionTile(item: x))])); } }
class Metric extends StatelessWidget { final String label; final num value; final Color color; const Metric({super.key, required this.label, required this.value, required this.color}); @override Widget build(BuildContext context) => Card(child: Padding(padding: const EdgeInsets.all(15), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(label, style: const TextStyle(color: Colors.grey)), const SizedBox(height: 5), Text(money(value), style: TextStyle(color: color, fontWeight: FontWeight.bold))]))); }
class TransactionsTab extends StatefulWidget { const TransactionsTab({super.key}); @override State<TransactionsTab> createState() => _TransactionsTabState(); }
class _TransactionsTabState extends State<TransactionsTab> { final amount = TextEditingController(), description = TextEditingController(); String type = 'expense'; Future<void> add() async { try { await context.read<FinanceStore>().add(double.parse(amount.text), description.text, type); amount.clear(); description.clear(); if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Đã thêm giao dịch'))); } catch (e) { if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(e.toString()))); } } @override Widget build(BuildContext context) { final s = context.watch<FinanceStore>(); return ListView(padding: const EdgeInsets.all(18), children: [Card(child: Padding(padding: const EdgeInsets.all(16), child: Column(children: [TextField(controller: amount, keyboardType: TextInputType.number, decoration: const InputDecoration(labelText: 'Số tiền')), TextField(controller: description, decoration: const InputDecoration(labelText: 'Mô tả')), DropdownButtonFormField(value: type, items: const [DropdownMenuItem(value: 'expense', child: Text('Chi tiêu')), DropdownMenuItem(value: 'income', child: Text('Thu nhập'))], onChanged: (v) => setState(() => type = v!), decoration: const InputDecoration(labelText: 'Loại')), const SizedBox(height: 10), FilledButton(onPressed: add, child: const Text('Lưu giao dịch'))]))), const SizedBox(height: 18), ...s.transactions.map((x) => TransactionTile(item: x, onDelete: () => s.remove(x['id'])))]; } }
class TransactionTile extends StatelessWidget { final dynamic item; final VoidCallback? onDelete; const TransactionTile({super.key, required this.item, this.onDelete}); @override Widget build(BuildContext context) { final income = item['type'] == 'income'; return ListTile(leading: CircleAvatar(backgroundColor: income ? Colors.green.shade50 : Colors.red.shade50, child: Icon(income ? Icons.arrow_upward : Icons.arrow_downward, color: income ? Colors.green : Colors.red)), title: Text(item['description']), subtitle: Text(item['created_at'].toString().split(' ').first), trailing: Row(mainAxisSize: MainAxisSize.min, children: [Text('${income ? '+' : '-'}${money(item['amount'])}', style: TextStyle(color: income ? Colors.green : Colors.red, fontWeight: FontWeight.bold)), if (onDelete != null) IconButton(onPressed: onDelete, icon: const Icon(Icons.delete_outline))])); } }
class ReportTab extends StatelessWidget { const ReportTab({super.key}); @override Widget build(BuildContext context) { final s = context.watch<FinanceStore>(); final total = (s.report['income'] ?? 0) + (s.report['expense'] ?? 0); return ListView(padding: const EdgeInsets.all(18), children: [const Text('Báo cáo tài chính', style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold)), const SizedBox(height: 18), Metric(label: 'Số dư ròng', value: s.report['balance'] ?? 0, color: Colors.blue), Metric(label: 'Tổng thu nhập', value: s.report['income'] ?? 0, color: Colors.green), Metric(label: 'Tổng chi tiêu', value: s.report['expense'] ?? 0, color: Colors.red), const SizedBox(height: 12), Text(total == 0 ? 'Chưa có dữ liệu.' : (s.report['balance'] >= 0 ? 'Bạn đang duy trì dòng tiền dương.' : 'Chi tiêu đang cao hơn thu nhập.'), style: const TextStyle(color: Colors.grey))]); } }
